type Query {
  dailyLog(date: String!): DailyLog!
}

enum MealType {
  BREAKFAST
  LUNCH
  DINNER
  SNACK
  CUSTOM
}

type DailyLog {
  date: String!
  logGroups: [LogGroup!]!
  foodLogs: [FoodLog!]!
  dailyNutritionTarget: DailyNutritionTarget!
}

type DailyNutritionTarget {
  calories: Float!
  protein: Float!
  carbs: Float!
  fats: Float!
}

type LogGroup {
  id: ID!
  name: String!
  mealType: MealType!
  date: String!
  computeFromFoodLogs: Boolean!
  totalCalories: Float!
  totalProtein: Float!
  totalCarbs: Float!
  totalFats: Float!
}

type FoodLog {
  id: ID!
  logGroupId: ID
  name: String!
  date: String!
  time: String!
  calories: Float!
  protein: Float!
  carbs: Float!
  fats: Float!
}
