INSERT INTO users (
    email,
    password_hash,
    first_name,
    last_name,
    is_admin,
    created_at
)
VALUES
    (
        'admin@balanced.local',
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOHiqO7qK8G7DKVNJ3.jZioew1tL1L0A6',
        'Admin',
        'User',
        TRUE,
        now()
    ),
    (
        'user@balanced.local',
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOHiqO7qK8G7DKVNJ3.jZioew1tL1L0A6',
        'Demo',
        'User',
        FALSE,
        now()
    );

INSERT INTO foods (
    name,
    brand,
    source,
    external_id,
    serving_size,
    serving_unit,
    calories_per_100g,
    protein_per_100g,
    carbs_per_100g,
    fats_per_100g,
    raw_source_json,
    created_by_user_id,
    created_at,
    updated_at
)
VALUES
    (
        'Chicken breast',
        NULL,
        'CUSTOM',
        NULL,
        100,
        'g',
        165,
        31,
        0,
        3.6,
        NULL,
        NULL,
        now(),
        now()
    ),
    (
        'Cooked white rice',
        NULL,
        'CUSTOM',
        NULL,
        100,
        'g',
        130,
        2.7,
        28,
        0.3,
        NULL,
        NULL,
        now(),
        now()
    ),
    (
        'Greek yogurt',
        'Generic',
        'CUSTOM',
        NULL,
        100,
        'g',
        59,
        10,
        3.6,
        0.4,
        NULL,
        NULL,
        now(),
        now()
    ),
    (
        'Banana',
        NULL,
        'CUSTOM',
        NULL,
        100,
        'g',
        89,
        1.1,
        23,
        0.3,
        NULL,
        NULL,
        now(),
        now()
    ),
    (
        'Homemade protein pancakes',
        NULL,
        'CUSTOM',
        NULL,
        100,
        'g',
        205,
        14,
        24,
        6,
        NULL,
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        now(),
        now()
    );

INSERT INTO food_log_groups (
    user_id,
    name,
    meal_type,
    date,
    compute_from_food_logs,
    total_calories,
    total_protein,
    total_carbs,
    total_fats,
    created_at,
    updated_at
)
VALUES
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        'Breakfast',
        'BREAKFAST',
        CURRENT_DATE,
        TRUE,
        0,
        0,
        0,
        0,
        now(),
        now()
    ),
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        'Lunch',
        'LUNCH',
        CURRENT_DATE,
        TRUE,
        0,
        0,
        0,
        0,
        now(),
        now()
    ),
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        'Yesterday dinner',
        'DINNER',
        CURRENT_DATE - INTERVAL '1 day',
        TRUE,
        0,
        0,
        0,
        0,
        now(),
        now()
    );

INSERT INTO food_logs (
    user_id,
    group_id,
    food_id,
    name,
    quantity,
    unit,
    calories,
    protein,
    carbs,
    fats,
    notes,
    date,
    time,
    created_at,
    updated_at
)
VALUES
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        (SELECT id FROM food_log_groups WHERE name = 'Breakfast' AND user_id = (SELECT id FROM users WHERE email = 'user@balanced.local')),
        (SELECT id FROM foods WHERE name = 'Greek yogurt' AND created_by_user_id IS NULL LIMIT 1),
        'Greek yogurt',
        200,
        'g',
        118,
        20,
        7.2,
        0.8,
        'Simple breakfast',
        CURRENT_DATE,
        TIME '08:15',
        now(),
        now()
    ),
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        (SELECT id FROM food_log_groups WHERE name = 'Breakfast' AND user_id = (SELECT id FROM users WHERE email = 'user@balanced.local')),
        (SELECT id FROM foods WHERE name = 'Banana' AND created_by_user_id IS NULL LIMIT 1),
        'Banana',
        120,
        'g',
        106.8,
        1.32,
        27.6,
        0.36,
        NULL,
        CURRENT_DATE,
        TIME '08:20',
        now(),
        now()
    ),
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        (SELECT id FROM food_log_groups WHERE name = 'Lunch' AND user_id = (SELECT id FROM users WHERE email = 'user@balanced.local')),
        (SELECT id FROM foods WHERE name = 'Chicken breast' AND created_by_user_id IS NULL LIMIT 1),
        'Chicken breast',
        180,
        'g',
        297,
        55.8,
        0,
        6.48,
        'Grilled',
        CURRENT_DATE,
        TIME '13:00',
        now(),
        now()
    ),
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        (SELECT id FROM food_log_groups WHERE name = 'Lunch' AND user_id = (SELECT id FROM users WHERE email = 'user@balanced.local')),
        (SELECT id FROM foods WHERE name = 'Cooked white rice' AND created_by_user_id IS NULL LIMIT 1),
        'Cooked white rice',
        220,
        'g',
        286,
        5.94,
        61.6,
        0.66,
        NULL,
        CURRENT_DATE,
        TIME '13:05',
        now(),
        now()
    ),
    (
        (SELECT id FROM users WHERE email = 'user@balanced.local'),
        (SELECT id FROM food_log_groups WHERE name = 'Yesterday dinner' AND user_id = (SELECT id FROM users WHERE email = 'user@balanced.local')),
        (SELECT id FROM foods WHERE name = 'Homemade protein pancakes' AND created_by_user_id = (SELECT id FROM users WHERE email = 'user@balanced.local') LIMIT 1),
        'Homemade protein pancakes',
        250,
        'g',
        512.5,
        35,
        60,
        15,
        'Post-workout meal',
        CURRENT_DATE - INTERVAL '1 day',
        TIME '19:30',
        now(),
        now()
    );