ALTER TABLE users
    ADD COLUMN daily_calorie_target DOUBLE PRECISION NOT NULL DEFAULT 2000,
    ADD COLUMN daily_protein_target DOUBLE PRECISION NOT NULL DEFAULT 150,
    ADD COLUMN daily_carbs_target DOUBLE PRECISION NOT NULL DEFAULT 250,
    ADD COLUMN daily_fats_target DOUBLE PRECISION NOT NULL DEFAULT 70;
